import BUN from "../_assets/bun-js.png";
import GITB from "../_assets/git&github-b.svg";
import GIT from "../_assets/git&github.svg";
import JAVASCRIPT from "../_assets/javascript.png";
import NEXTB from "../_assets/next-js-b.svg";
import NEXTA from "../_assets/next-js.svg";
import EXPRESSA from "../_assets/node&exp.svg";
import EXPRESSB from "../_assets/node-b.svg";
import PY from "../_assets/python.svg";
import RP from "../_assets/raspberry-pi.svg";
import REACTNATIVE from "../_assets/react-native.svg";
import REACT from "../_assets/react.svg";
import RUST_ICON from "../_assets/rust.png";
import STORYBOOK from "../_assets/storybook.svg";
import TYPESCRIPT from "../_assets/ts.svg";
import VANILLA from "../_assets/vanilla-extract.png";
import VITEST from "../_assets/vitest.svg";

export const RN = REACTNATIVE;
export const JS = JAVASCRIPT;
export const TS = TYPESCRIPT;
export const REACT_PIC = REACT;
export const NEXT = NEXTA;
export const NEXT_B = NEXTB;
export const VANILLA_EXTRACT = VANILLA;
export const STORY_BOOK = STORYBOOK;
export const EXPRESS = EXPRESSA;
export const EXPRESS_B = EXPRESSB;
export const VT = VITEST;
export const BUN_JS = BUN;
export const PYTHON = PY;
export const GIT_MAIN = GIT;
export const GIT_SUB = GITB;
export const RASPI = RP;
export const RUST = RUST_ICON;
